Update configuration for docker
edgexfoundry/core-metadata-go pull request #14
Opened 2017-12-14 23:14 UTC by bullapse

Signed-off-by: Spencer Bull <spencer_bull@dell.com>

#10 Resolved
#11 Resolved
#13 Revision

2017-12-14 23:16 UTC, trcox commented on res/configuration-docker.json
> +	"LoggingRemoteURL": "http://edgex-core-logging:48061/api/v1/logs",
edgex-support-logging

2017-12-14 23:16 UTC, trcox commented on res/configuration-docker.json
> +	"NotificationSender": "core-metadata",
edgex-core-metadata

2017-12-14 23:17 UTC, trcox commented on res/configuration-docker.json
> +	"ServiceName": "core-metadata",
edgex-core-metadata

2017-12-14 23:17 UTC, trcox commented on res/configuration-docker.json
> +	"ApplicationName": "Metadata",
edgex-core-metadata

2017-12-14 23:17 UTC, trcox commented on res/configuration-docker.json
> -	"consulprofilesactive" : "docker;go",
keep this config for consul-client

2017-12-14 23:18 UTC, trcox requested changes
See inline comments

2017-12-15 00:32 UTC, bullapse commented
Fixed requested changes by @trcox

2017-12-15 05:51 UTC, trcox approved these changes

2017-12-15 05:51 UTC, merged